# Based on this template:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# https://hub.docker.com/luanst/c4build
image:
  luanst/c4build:latest

variables:
  GIT_CLEAN_FLAGS: none

# build the compiler executable
build:
  stage: build
  script:
    - ln -s /llvm ./llvm
    - make
  artifacts:
    paths:
      - build/debug/c4

# run tests using the binary built before
test:
  stage: test
  script:
    - python3 test.py --ci --verbose lexer parser sema
